name: Generate Total LOC Badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'   # every Sunday at midnight

jobs:
  count-loc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cloc jq gh

    - name: Clone all public repos and count LOC
      run: |
        mkdir repos || true
        gh repo list Kirito666codr --limit 100 --json nameWithOwner,isFork,visibility \
          -q '.[] | select(.isFork==false and .visibility=="public") | .nameWithOwner' > repos.txt

        echo "Counting lines..."
        TOTAL=0
        while read repo; do
          echo "Cloning $repo"
          gh repo clone "$repo" "repos/$(basename $repo)" -- -q
          CODE=$(cloc --json "repos/$(basename $repo)" | jq '.SUM.code // 0')
          echo "$repo: $CODE"
          TOTAL=$((TOTAL + CODE))
        done < repos.txt

        echo "Total lines: $TOTAL"
        mkdir -p badge
        echo "{\"schemaVersion\":1,\"label\":\"total LOC\",\"message\":\"${TOTAL}\",\"color\":\"blue\"}" > badge/loc-badge.json

    - name: Upload badge to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./badge
